### ISSUE TITLE
Question about architecture

### ISSUE THREAD

**Issue by benjiqq** [paulczar/docker-wordpress#1]
This looks very cool. Does this balance between identical container images or are these separate installs? I'm trying to figure out how many parallel WP installs could best share resources.

**Comment by paulczar** [comment]
They're identical at launch...  but will change over time.    To be really useful needs some way to sync the filesystem between the wordpress containers that are running ( if an admin uploads an image it would only upload to the one server ) ...  maybe use docker volumes ?
